gitSourceBranch = "master"
changelog = true
classOrder = [
    "RoCord",
    "Webhook",
    "Embed",
    "Utils"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright Â© 2022 GGshor. Built with Moonwave and Docusaurus"